project_id = "envewfudiyxmnuefbdow"

[functions.analyze-site]
verify_jwt = false

[functions.generate-content-plan]
verify_jwt = false

[functions.seo-analysis]
verify_jwt = false

[functions.generate-blog]
verify_jwt = false
